version: "3.1"
services:
  postgres:
    image: postgres:12.8
    container_name: pg_master
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ~/pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  slave:
    image: postgres:12.8
    container_name: pg_slave
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ~/pg_data_slave:/var/lib/postgresql/data
    ports:
      - 54322:5432
networks: {}
