services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    restart: unless-stopped
    ports:
      - "8903:8080"
    environment:
      - BASE_URL=http://localhost:8903/
    volumes:
      - ./searxng_settings:/etc/searxng

