services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - /dev_tool/docker/docker_data/ollama-data:/root/.ollama
    restart: unless-stopped
